version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"  # Mapea el puerto del contenedor al puerto 3000 del host
    volumes:
      - .:/app        # Mapea el directorio actual al contenedor
      - /app/node_modules  # Evita que sobrescriba los node_modules del contenedor
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm start  # Ejecuta npm start para iniciar la aplicación en modo desarrollo
